// <auto-generated />
namespace DOAN_WEB_NC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ThemCotDiemThi_BangChiTietDiem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ThemCotDiemThi_BangChiTietDiem));
        
        string IMigrationMetadata.Id
        {
            get { return "202005301312382_ThemCotDiemThi_BangChiTietDiem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
